name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app
        
      - name: Install Gems
        run: bundle install

      - name: Install CocoaPods dependencies
        run: pod install

      - name: Run unit tests
        run: bundle exec fastlane test_unit
        continue-on-error: true

      - name: Run UI tests
        run: bundle exec fastlane test_ui
        continue-on-error: true

      - name: Run accessibility tests
        run: bundle exec fastlane test_a11y
        continue-on-error: true
