name: iOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
 
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'
        
      - name: Install Gems
        run: bundle install

      - name: Install CocoaPods dependencies
        run: pod install

      - name: Run unit tests
        run: bundle exec fastlane test_unit

      - name: Run UI tests
        run: bundle exec fastlane test_ui

      - name: Run accessibility tests
        run: bundle exec fastlane test_a11y
